import "./globals.css";

export const metadata = {
  title: "Dot NB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-50 text-gray-900 cz-shortcut-listen=false`}
      >
        {children}
      </body>
    </html>
  );
}
